-- AlterTable
ALTER TABLE "canvases" ALTER COLUMN "tags" SET DEFAULT ARRAY[]::VARCHAR(255)[];

-- AlterTable
ALTER TABLE "frames" ADD COLUMN     "allowedMints" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isTopUp" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "owner" VARCHAR(255);

-- AlterTable
ALTER TABLE "templates" ALTER COLUMN "tags" SET DEFAULT ARRAY[]::VARCHAR(255)[];
